/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Register: () => import('#controllers/auth/register_controller'),
    RequestPasswordReset: () => import('#controllers/auth/request_password_reset_controller'),
    ResetPassword: () => import('#controllers/auth/reset_password_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
}
