/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Register: () => import('#controllers/auth/register_controller'),
    RequestPasswordReset: () => import('#controllers/auth/request_password_reset_controller'),
    ResetPassword: () => import('#controllers/auth/reset_password_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
  contact: {
    Contact: () => import('#controllers/contact/contact_controller'),
  },
  HomePublic: () => import('#controllers/home_public_controller'),
  menus: {
    Menus: () => import('#controllers/menus/menus_controller'),
    Pictures: () => import('#controllers/menus/pictures_controller'),
    AdminMenus: () => import('#controllers/menus/admin_menus_controller'),
  },
  notice: {
    RegisterNotice: () => import('#controllers/notice/register_notice_controller'),
    ValidateNotice: () => import('#controllers/notice/validate_notice_controller'),
  },
  orders: {
    CancelOrder: () => import('#controllers/orders/cancel_order_controller'),
    ClientOrders: () => import('#controllers/orders/client_orders_controller'),
    Order: () => import('#controllers/orders/order_controller'),
    OrderMaterialLoan: () => import('#controllers/orders/order_material_loan_controller'),
    OrderStatus: () => import('#controllers/orders/order_status_controller'),
    OrdersManagement: () => import('#controllers/orders/orders_management_controller'),
  },
  profile: {
    Profile: () => import('#controllers/profile/profile_controller'),
  },
}
