/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Register: () => import('#controllers/auth/register_controller'),
    RequestPasswordReset: () => import('#controllers/auth/request_password_reset_controller'),
    ResetPassword: () => import('#controllers/auth/reset_password_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
  contact: {
    Contact: () => import('#controllers/contact/contact_controller'),
  },
  HomePublic: () => import('#controllers/home_public_controller'),
  menus: {
    Menus: () => import('#controllers/menus/menus_controller'),
    Pictures: () => import('#controllers/menus/pictures_controller'),
  },
  orders: {
    Order: () => import('#controllers/orders/order_controller'),
    OrderStatus: () => import('#controllers/orders/order_status_controller'),
    OrdersManagement: () => import('#controllers/orders/orders_management_controller'),
    ClientOrders: () => import('#controllers/orders/client_orders_controller'),
  },
}
