/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AllergenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'updatedAt'] as const
  $columns = AllergenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DietSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'updatedAt'] as const
  $columns = DietSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ThemeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'updatedAt'] as const
  $columns = ThemeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['adress', 'city', 'country', 'createdAt', 'email', 'firstname', 'id', 'lastname', 'password', 'passwordChange', 'passwordReset', 'phone', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare adress: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstname: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastname: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare passwordChange: boolean
  @column()
  declare passwordReset: boolean
  @column()
  declare phone: string | null
  @column()
  declare roleId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
